//! `ExternalReference` and `OpaqueExternalObject`.
//!
//! Per `spec/domain-model.md` §"Interoperability entities":
//! ```text
//! ExternalReference {
//!   id, source_path, source_kind, resolved_artifact_hash | null,
//!   display_transform, status,
//! }
//! OpaqueExternalObject {
//!   id, source_format, source_version, external_type, external_handle,
//!   owner_external_handle, raw_payload, proxy_graphics | null,
//!   preservation_status, diagnostics[],
//! }
//! ```
//!
//! And per §"Representation and reference invariants":
//! 6. External references are metadata/links; their resolved content is
//!    never silently merged into the host drawing.
//! 7. Opaque external objects retain their original handle/ownership
//!    metadata independently of canonical IDs.
//!
//! And the explicit invariant on `OpaqueExternalObject`:
//! > Invariant: opaque objects can never silently disappear during an
//! > otherwise successful round trip.
//!
//! Frozen-contract invariants honored here:
//! - `raw_payload` is `Vec<u8>` (bytes); preserved verbatim through
//!   round trips (per WO-003-AC03).
//! - `proxy_graphics` is `Option<Vec<u8>>` (null or bytes).
//! - `diagnostics` is `Vec<String>` (the spec lists `diagnostics[]`
//!   without a structured type; W003 stores opaque strings — the
//!   canonical model preserves them verbatim through round trips per
//!   WO-003-AC03).
//! - `preservation_status` is the closed `PreservationStatus` enum.
//! - Unknown fields are rejected (`#[serde(deny_unknown_fields)]`).
//!
//! W003 does NOT implement:
//! - the actual proxy-graphics RENDERING (that's an interop/visual
//!   concern for W011/W012/W015);
//! - cross-reference RESOLUTION (that's an interop concern for W011);
//! - any DIAGNOSTIC-LEVEL classification beyond the string form (the
//!   spec doesn't enumerate levels, so W003 doesn't invent them).
//!
//! W003 implements the data containers and the round-trip preservation
//! invariant only.

use aeccad_core_geometry::Transform2D;
use serde::{Deserialize, Serialize};

use crate::identity::{ExternalObjectId, ExternalRefId};
use crate::value_types::{PreservationStatus, SourceKind};

/// External reference (an Xref, image, PDF underlay, etc.). The
/// reference is METADATA ONLY — per invariant #6, the resolved
/// content is never silently merged into the host drawing. The
/// resolved content lives in a separate artifact (referenced by
/// `resolved_artifact_hash`); the host drawing only stores the link.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExternalReference {
    /// Stable, opaque external-reference identity.
    pub id: ExternalRefId,
    /// Source path (filesystem path or URI). Opaque string; the
    /// canonical model does not interpret the path (the importer /
    /// resolver does).
    pub source_path: String,
    /// Source kind (closed enum).
    pub source_kind: SourceKind,
    /// Hash of the resolved artifact, if the reference has been
    /// resolved. `None` means unresolved.
    pub resolved_artifact_hash: Option<String>,
    /// Display transform applied to the resolved content when placed
    /// in the host drawing. The transform is metadata on the
    /// reference, NOT an entity in the entity table — per invariant
    /// #6, the resolved content is never silently merged.
    pub display_transform: Transform2D,
    /// Reference status. Reuses the closed `PreservationStatus` enum
    /// (the spec lists `status` without a separate enum — the
    /// most-conservative reading is that it shares the preservation
    /// status set; inventing a new enum would be unspecified
    /// semantics).
    pub status: PreservationStatus,
}

/// Opaque external object — an object whose kind is known to the
/// source format but is not (yet) supported by this version of the
/// canonical model. Per architecture-lock §5 "Unknown-object
/// preservation" and §7 "No silent data loss", the object MUST be
/// preserved as opaque bytes through round trips.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OpaqueExternalObject {
    /// Stable, opaque identity. Independent of `external_handle`
    /// (per invariant #7: "Opaque external objects retain their
    /// original handle/ownership metadata independently of canonical
    /// IDs"). The canonical ID is generated by the canonical boundary
    /// (importer/command engine); the `external_handle` is preserved
    /// separately as a metadata field.
    pub id: ExternalObjectId,
    /// Source format identifier (e.g. "DWG-R2018", "DXF-R12").
    pub source_format: String,
    /// Source format version.
    pub source_version: String,
    /// External type name (e.g. "ACAD_TABLE", "HATCH"). Opaque string;
    /// the canonical model does not interpret it.
    pub external_type: String,
    /// Original handle in the source format. Preserved verbatim
    /// through round trips; never elevated to a primary ID.
    pub external_handle: String,
    /// Owning object's external handle (or empty string if the object
    /// is a root in the source format). Preserved verbatim.
    pub owner_external_handle: String,
    /// Raw bytes of the unsupported object. Preserved verbatim through
    /// round trips (per WO-003-AC03).
    pub raw_payload: Vec<u8>,
    /// Optional proxy graphics bytes (a rendering fallback). `None`
    /// if the source format did not provide proxy graphics.
    pub proxy_graphics: Option<Vec<u8>>,
    /// Preservation status (closed enum). Per the spec invariant,
    /// `NotPreserved` MUST be accompanied by an explicit diagnostic
    /// (the canonical model never silently drops content — per
    /// architecture-lock §7).
    pub preservation_status: PreservationStatus,
    /// Diagnostics about the preservation. Preserved verbatim
    /// through round trips.
    pub diagnostics: Vec<String>,
}

impl ExternalReference {
    /// Construct an external reference.
    #[must_use]
    pub fn new(
        id: ExternalRefId,
        source_path: String,
        source_kind: SourceKind,
        resolved_artifact_hash: Option<String>,
        display_transform: Transform2D,
        status: PreservationStatus,
    ) -> Self {
        Self {
            id,
            source_path,
            source_kind,
            resolved_artifact_hash,
            display_transform,
            status,
        }
    }
}

impl OpaqueExternalObject {
    /// Construct an opaque external object with the given fields.
    #[must_use]
    pub fn new(
        id: ExternalObjectId,
        source_format: String,
        source_version: String,
        external_type: String,
        external_handle: String,
        owner_external_handle: String,
        raw_payload: Vec<u8>,
        proxy_graphics: Option<Vec<u8>>,
        preservation_status: PreservationStatus,
        diagnostics: Vec<String>,
    ) -> Self {
        Self {
            id,
            source_format,
            source_version,
            external_type,
            external_handle,
            owner_external_handle,
            raw_payload,
            proxy_graphics,
            preservation_status,
            diagnostics,
        }
    }
}

#[cfg(test)]
mod tests {
    // Evidence: WO-003-AC03 — opaque external objects survive load/save
    // of the canonical representation; raw_payload, proxy_graphics,
    // external_handle, owner_external_handle, diagnostics are all
    // preserved verbatim through a round trip. Count is unchanged
    // (per the spec invariant "opaque objects can never silently
    // disappear during an otherwise successful round trip").
    // Evidence: WO-003-AC02 — ExternalReference round-trips.
    // Evidence: WO-003-AC01 — external_handle is metadata, NOT the
    // primary ID (independent fields, both preserved).

    use super::*;
    use crate::identity::TestIdGenerator;
    use aeccad_core_geometry::Transform2D;

    fn fixture_xref() -> ExternalReference {
        let mut g = TestIdGenerator::new(0);
        ExternalReference::new(
            crate::identity::next_external_ref_id(&mut g),
            "/host/site-plan.dwg".to_string(),
            SourceKind::Xref,
            Some("sha256:deadbeef".to_string()),
            Transform2D::IDENTITY,
            PreservationStatus::PreservedOpaque,
        )
    }

    fn fixture_opaque() -> OpaqueExternalObject {
        let mut g = TestIdGenerator::new(0);
        OpaqueExternalObject::new(
            crate::identity::next_external_object_id(&mut g),
            "DWG-R2018".to_string(),
            "AC1027".to_string(),
            "ACAD_TABLE".to_string(),
            "1F".to_string(),
            "0A".to_string(),
            vec![0xDE, 0xAD, 0xBE, 0xEF, 0x00, 0xFF],
            Some(vec![0x01, 0x02, 0x03, 0x04]),
            PreservationStatus::DegradedOpaque,
            vec!["table style reference missing".to_string()],
        )
    }

    #[test]
    fn external_reference_field_set_matches_spec() {
        let x = fixture_xref();
        let v = serde_json::to_value(&x).expect("serialize");
        let obj = v.as_object().expect("object");
        let mut keys: Vec<&str> = obj.keys().map(String::as_str).collect();
        keys.sort_unstable();
        assert_eq!(
            keys,
            [
                "display_transform",
                "id",
                "resolved_artifact_hash",
                "source_kind",
                "source_path",
                "status",
            ]
        );
    }

    #[test]
    fn opaque_object_field_set_matches_spec() {
        let o = fixture_opaque();
        let v = serde_json::to_value(&o).expect("serialize");
        let obj = v.as_object().expect("object");
        let mut keys: Vec<&str> = obj.keys().map(String::as_str).collect();
        keys.sort_unstable();
        assert_eq!(
            keys,
            [
                "diagnostics",
                "external_handle",
                "external_type",
                "id",
                "owner_external_handle",
                "preservation_status",
                "proxy_graphics",
                "raw_payload",
                "source_format",
                "source_version",
            ]
        );
    }

    #[test]
    fn opaque_object_survives_roundtrip_verbatim() {
        // Evidence: WO-003-AC03 — every field survives a round trip
        // with byte-level fidelity (raw_payload, proxy_graphics) and
        // string-level fidelity (handles, type, version, diagnostics).
        let o = fixture_opaque();
        let j = serde_json::to_string(&o).expect("serialize");
        let back: OpaqueExternalObject = serde_json::from_str(&j).expect("deserialize");
        assert_eq!(o, back, "opaque object survives round trip verbatim");
        // Specifically, the bytes are unchanged.
        assert_eq!(o.raw_payload, back.raw_payload);
        assert_eq!(o.proxy_graphics, back.proxy_graphics);
        // And the external handle is preserved SEPARATELY from the
        // canonical id (invariant #7).
        assert_eq!(o.external_handle, back.external_handle);
        assert_eq!(o.id, back.id);
        assert_ne!(
            format!("{}", o.id),
            o.external_handle,
            "canonical id and external handle are independent"
        );
    }

    #[test]
    fn opaque_object_count_unchanged_after_roundtrip_collection() {
        // Evidence: WO-003-AC03 — "opaque objects can never silently
        // disappear during an otherwise successful round trip." A
        // collection of opaque objects round-trips with the same count
        // and same IDs.
        let mut g = TestIdGenerator::new(0);
        let originals: Vec<OpaqueExternalObject> = (0..5)
            .map(|i| {
                OpaqueExternalObject::new(
                    crate::identity::next_external_object_id(&mut g),
                    "DWG-R2018".to_string(),
                    "AC1027".to_string(),
                    format!("ACAD_TYPE_{i}"),
                    format!("{i:X}"),
                    String::new(),
                    vec![i as u8; 32],
                    None,
                    PreservationStatus::PreservedOpaque,
                    Vec::new(),
                )
            })
            .collect();
        let j = serde_json::to_string(&originals).expect("serialize");
        let back: Vec<OpaqueExternalObject> = serde_json::from_str(&j).expect("deserialize");
        assert_eq!(originals.len(), back.len(), "count unchanged");
        for (a, b) in originals.iter().zip(back.iter()) {
            assert_eq!(a.id, b.id, "id preserved");
            assert_eq!(a.raw_payload, b.raw_payload, "payload preserved");
        }
    }

    #[test]
    fn degraded_opaque_object_survives_with_diagnostics() {
        // Evidence: WO-003-AC03 — even a DegradedOpaque object is
        // preserved with its diagnostics (no silent data loss per
        // architecture-lock §7).
        let o = OpaqueExternalObject::new(
            {
                let mut g = TestIdGenerator::new(0);
                crate::identity::next_external_object_id(&mut g)
            },
            "DWG-R2018".to_string(),
            "AC1027".to_string(),
            "ACAD_TABLE".to_string(),
            "1F".to_string(),
            String::new(),
            vec![0xAB; 16],
            None,
            PreservationStatus::DegradedOpaque,
            vec![
                "table style reference missing".to_string(),
                "fallback to placeholder graphics".to_string(),
            ],
        );
        let j = serde_json::to_string(&o).expect("serialize");
        let back: OpaqueExternalObject = serde_json::from_str(&j).expect("deserialize");
        assert_eq!(o.preservation_status, back.preservation_status);
        assert_eq!(o.diagnostics, back.diagnostics);
        assert_eq!(o.raw_payload, back.raw_payload);
    }

    #[test]
    fn external_reference_roundtrips() {
        let x = fixture_xref();
        let j = serde_json::to_string(&x).expect("serialize");
        let back: ExternalReference = serde_json::from_str(&j).expect("deserialize");
        assert_eq!(x, back);
    }

    #[test]
    fn external_reference_rejects_unknown_fields() {
        let x = fixture_xref();
        let mut v = serde_json::to_value(&x).expect("serialize");
        v.as_object_mut()
            .expect("object")
            .insert("surprise".to_string(), serde_json::Value::Null);
        assert!(serde_json::from_value::<ExternalReference>(v).is_err());
    }

    #[test]
    fn opaque_object_rejects_unknown_fields() {
        let o = fixture_opaque();
        let mut v = serde_json::to_value(&o).expect("serialize");
        v.as_object_mut()
            .expect("object")
            .insert("surprise".to_string(), serde_json::Value::Null);
        assert!(serde_json::from_value::<OpaqueExternalObject>(v).is_err());
    }
}
